### ISSUE TITLE
Add an associated string reason to DataError

### ISSUE THREAD

**Issue by loudnate** [mddub/dexcom-share-client-swift#3]
@channemann is getting `DataError` a few times per day without knowing what the core issue is.

**Comment by mddub** [comment]
Added more context for debugging in https://github.com/mddub/dexcom-share-client-swift/commit/208774. Let me know what else I can do to help.

**Comment by loudnate** [comment]
Awesome. Can you bump the version string and tag a release for @channemann and @eyim to try?

**Comment by mddub** [comment]
Yep, just pushed `v0.1.1`.
